name: Release CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  ci:
    name: CI Init
    runs-on: [ self-hosted, Linux ]
    outputs:
      action: ${{ steps.init.outputs.action }}
    steps:
      - id: init
        uses: localazy/release/init@v2

  prepare:
    name: Prepare Release PR
    needs: ci
    if: needs.ci.outputs.action == 'prepare'
    runs-on: [ self-hosted, Linux ]
    steps:
      - uses: localazy/release/prepare@v2
        with:
          node-version-file: .nvmrc
          app-id: ${{ secrets.AUTH_APP_ID }}
          app-key: ${{ secrets.AUTH_APP_KEY }}
          badges: true

  publish:
    name: Publish Release
    needs: [ ci ]
    if: needs.ci.outputs.action == 'publish'
    runs-on: [ self-hosted, Linux ]
    steps:
      - uses: localazy/release/publish@v2
        with:
          node-version-file: .nvmrc
          app-id: ${{ secrets.AUTH_APP_ID }}
          app-key: ${{ secrets.AUTH_APP_KEY }}
          npm-publish: public
          npm-token: ${{ secrets.NPM_AUTH_TOKEN_PUBLIC }}
